version: "3.9"

name: "xyz-prod"

services:
  db:
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    restart: always
    environment:
      GH_CLIENT_ID: a569cafe591e507b13ca
      AWS_S3_BLOB_BUCKET: hitsave-prod-blobs

  nginx:
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      NGINX_HOST: hitsave.io
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  web:
    restart: always
    environment:
      GH_CLIENT_ID: a569cafe591e507b13ca
      HITSAVE_WEB_URL: https://hitsave.io

volumes:
  pgdata:
    driver_opts:
      type: "xfs"
      device: "/dev/xvdb"
