version: "3.9"

name: "xyz-prod"

services:
  db:
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    environment:
      GH_CLIENT_ID: a569cafe591e507b13ca

  nginx:
    environment:
      NGINX_HOST: hitsave.io

  web:
    environment:
      GH_CLIENT_ID: a569cafe591e507b13ca
      HITSAVE_WEB_URL: http://hitsave.io

volumes:
  pgdata:
    driver_opts:
      type: "xfs"
      device: "/dev/xvdb"
