# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Client Python Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          cache: 'pip'
          cache-dependency-path: |
            client/dev_requirements.txt
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: client
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f dev_requirements.txt ]; then pip install -r dev_requirements.txt; fi
          python -m pip install -e .
      - name: Build documentation
        working-directory: client/docs
        run: make html
      - name: Lint with black
        working-directory: client
        run: |
          black . --check --verbose
      - name: Test with pytest
        working-directory: client
        env:
          # [todo] need integration tests really.
          HITSAVE_API_KEY: ${{ secrets.HITSAVE_API_KEY }}
          HITSAVE_URL: https://api.hitsave.io
        run: |
          pytest
