# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Client Python Package

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CACHE_DIR: "~/.cache"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Hatch
        id: cache-hatch
        uses: actions/cache@v3
        with:
          path: ${{env.CACHE_DIR}}
          key: ${{ runner.os }}-${{ github.run_id }} # Can use time based key as well
          restore-keys: |
            ${{ runner.os }}
      - name: Install Hatch
        run: pipx install hatch
      - name: Run tests
        working-directory: "./client"
        run: hatch run test:test
      - name: Build documentation
        working-directory: "./client"
        run: hatch run docs:build
      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: client/docs/_build/html
      - name: Build dist
        working-directory: "./client"
        run: hatch build
      - name: Upload dist artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: client/dist
      - name: Publish on PyPI
        if: github.ref == 'refs/heads/main'
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: e.w.ayers
          password: ${{ secrets.pypi_password }}
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
